# Configuração da API Exchange Rate API
# Altere a chave abaixo caso deseje usar uma chave diferente

api.key=9026bfb0183b94379a5ef93b
api.base.url=https://v6.exchangerate-api.com/v6
api.timeout=5000
